name: Linux release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install packages
      run: |
        sudo apt-get install libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit==2.13.0
        pip install pyinstaller==4.3
        pip install -r requirements.txt
    - name: Run pyinstaller
      run: |
        pyinstaller --add-data src/style.css:. --hidden-import pkg_resources --runtime-hook src/pyinstaller_entry_hook.py -n butter entry.py --distpath butter-${{ env.RELEASE_VERSION }}/
    - name: Create archive
      run: |
        tar -cf butter-${{ env.RELEASE_VERSION }}.tar.gz butter-${{ env.RELEASE_VERSION }}/
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "butter-${{ env.RELEASE_VERSION }}.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
